name: 临帖宝
description: 书法临帖工具，不止于此！
full_description: '关于临帖宝APP<br>
<br>- 超过150本古字帖书籍、30位书法大家代表作，并持续更新。
<br>- 超过10万首古诗词文，书法创作中的好帮手。
<br>- 书法中常见异体字，一查便知。'
android: https://lintiebao.com/
iOS: https://lintiebao.com/
web: https://lintiebao.com/
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://lintiebao.com/
companies:
  - url: https://lintiebao.com/
    image: assets/images/icon.png
  - url: https://lintiebao.com/
    image: assets/images/icon.png
